### PR TITLE
Datto REST API - SaaS Bulk Seat Change

### LINKED ISSUE #2: [Bug]: SaaS Bulk Seat Update Endpoint should be SET with PUT call.
### What happened?

SaaS Bulk Seat Assignment endpoint is actually an HTTP PUT call, and so the current implementation with the `Get-DattoBulkSeatAssignment` function does not work as expected.

```PowerShell
Get-DattoBulkSeatAssignment

cmdlet Get-DattoBulkSeatAssignment at command pipeline position 1
Supply values for the following parameters:
saasCustomerId: 123456
externalSubscriptionId: Classic:Office365:123456
WARNING: The [ Datto_invokeParameters, Datto_queryString, & Datto_CmdletNameParameters ] variables can provide extra details
Invoke-DattoRequest : Invoke-DattoRequest : [ /saas/123456/Classic:Office365:123465/bulkSeatAssignment ] not found!
At C:\Users\first.last\OneDrive\Documents\WindowsPowerShell\Modules\DattoAPI\2.2.1\DattoAPI.psm1:2385 char:9
+         Invoke-DattoRequest -method GET -resource_Uri $resource_Uri - ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-DattoRequest
```

### Expected behavior?

Seat change in the UI as expected for the SaaS Protection Organization seat,

Example response received for valid response body received from bulk seat change endpoint.

### Possible Solution?

Should be able to have this work with the proper PUT, working on a fork to merge into the dev branch. This would be my first merge to another public repo and contributing, so any feedback is well appreciated.

Trying to get the conversation started on everything expected here for the module, and what may be needed for the proper implementation.

### PowerShell Version

5.1 - (PowerShell)

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```PowerShell
Get-DattoBulkSeatAssignment

cmdlet Get-DattoBulkSeatAssignment at command pipeline position 1
Supply values for the following parameters:
saasCustomerId: 123456
externalSubscriptionId: Classic:Office365:123456
WARNING: The [ Datto_invokeParameters, Datto_queryString, & Datto_CmdletNameParameters ] variables can provide extra details
Invoke-DattoRequest : Invoke-DattoRequest : [ /saas/123456/Classic:Office365:123465/bulkSeatAssignment ] not found!
At C:\Users\first.last\OneDrive\Documents\WindowsPowerShell\Modules\DattoAPI\2.2.1\DattoAPI.psm1:2385 char:9
+         Invoke-DattoRequest -method GET -resource_Uri $resource_Uri - ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-DattoRequest
```

### Help Commands

```PowerShell
$PSversionTable

$PSversionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  3803


Get-Package -Name xxxModuleNamexxx | Select-Object Name,Version,Source,ProviderName
```PowerShell
Get-Package DattoApi | Select-Object Name,Version,Source,ProviderName

Name     Version Source                                   ProviderName
----     ------- ------                                   ------------
DattoAPI 2.2.1   https://www.powershellgallery.com/api/v2 PowerShellGet
```

Get-ComputerInfo -Property @( 'OsName', 'OsVersion', 'OsOperatingSystemSKU', 'OSArchitecture', 'WindowsVersion', 'WindowsBuildLabEx', 'OsLanguage', 'OsMuiLanguages' )
```PowerShell
OsName               : Microsoft Windows 10 Enterprise
OsVersion            : 10.0.19045
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by cksapp**
# Pull Request
Datto SaaS Protection - Bulk Seat Change REST API Function

## Description

Fixes SaaS Bulk Seat Assignment Function added in 5cabe17 to support API endpoint.

Resolves: [#2 [Bug]: SaaS Bulk Seat Update Endpoint should be SET with PUT call.](https://github.com/Celerium/Datto-PowerShellWrapper/issues/2)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] General code cleanup (non-breaking change which improves readability)

## Checklist

- [X] I have reviewed the [Contributing](https://github.com/Celerium/DattoAPI/blob/main/.github/CONTRIBUTING.md) guide
- [X] I am pulling to the **dev** branch
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## How Has This Been Tested?

Validated against expected behavior from API calls via Postman, changes were reflected in the Datto SaaS Protection service.

- [X] Postman
* **Before**

* **Postman API call**

* **Result**

---

- [X] PowerShell Wrapper Module
* **Before**

* **PowerShell Function**

* **Result**

### CODE REVIEW

**Comment by Celerium** [comment]
@cksapp, Thank you for the awesome contrubutions! Mostly everything looks good here so I am going to merge and make some tweaks to a few items.

#2

**Comment by cksapp** [comment]
Thanks @Celerium! I actually meant to also push a minor commit in 12f5790 as part of this, not anything major so otherwise the function works just as intended. Mainly updating the messaging and examples, not sure if the PR can be amended after being closed or it would require another pull request.

Otherwise feel free to simply copy the changes from there, and feel free to make any changes overall as you see fit for the module.
Glad to contribute 😄

**Comment by Celerium** [comment]
No worries, ill add those updates as well. I also found some other changes that Datto made to their API that ill be adding as well.

For the actionType where did you find the values of 'License', 'Pause', 'Unlicense'? I cant seem to find them in their API docs

**Comment by cksapp** [comment]
> No worries, ill add those updates as well. I also found some other changes that Datto made to their API that ill be adding as well.

Okay great, there were a few additional things I noticed in the docs that may have been missed or need to be updated so might try to work on another small PR to update those when I can.
I did notice the new additions to seats API as well but hadn't had a chance to review further. 

---

> For the actionType where did you find the values of 'License', 'Pause', 'Unlicense'? I cant seem to find them in their API docs

Regarding the actionType, I have to agree the documentation for the API is fairly sparse to say the least. Mostly determining the actionType was based on trial and error, as well as just a bit of insider knowledge.
_(I currently work within Datto's SaaS Protection product and scoured for information internally based on the changes from their dev team as no-one else was familiar)_. 😉

There does not appear to be any other mentions of additional actionTypes and testing with an actionType of something like `Archive` does not appear to accept any PUT and simply returns,
```json
{
    "code": "error.internal",
    "message": "An internal server error occurred"
}
```

On a side note to this, I **do** strongly believe we should make the note that both actionType, and seatType are case-sensitive and otherwise appear to require <u>PascalCase</u> as the call will return an error if not respected.

I presume this is due to the _*NIX_ backend systems being used. I am not sure if we **could/should** enforce the case-sensitivity for the input, or simply return the error and make the warning in the docs here.
 _We probably **could**, but as an API wrapper I feel its best to let most of the logic be handled by the module user_

**Pull request merged**
